### ISSUE TITLE
Can't find your country link isn't tappable

### ISSUE THREAD

**Issue by VladStrigunov** [onfido/onfido-ios-sdk#81] opened 2019-04-03 21:00 UTC
### What was the expected behaviour?
Tap on 'Can't find your country?' 
![expected_cant_find_country](https://user-images.githubusercontent.com/41125587/55495852-a75f5480-55f2-11e9-8c87-51a64cc4331e.png)

### What happened instead?
When user taps on 'Can't find your country?' prompt is not displayed.
'Can't find your country?' is not clickable.

### Version info:
Cocoapods (if applicable): 1.6
Onfido SDK (Debug/Release): 11.0
iOS: 12.2
Xcode: 10.2
Device/Simulator: Both
Device/Simulator language: en-US

### Integration configuration:

`
func config(for applicantId: String) -> OnfidoConfig? {
    let appearance = Appearance(
      primaryColor: UIColor.skyBlue,
      primaryTitleColor: UIColor.white,
      primaryBackgroundPressedColor: UIColor.white,
      secondaryBackgroundPressedColor: UIColor.white,
      fontRegular: "Lato-Regular",
      fontBold: "Lato-Bold")
    let configBuilder = OnfidoConfig.builder()
    configBuilder.withAppearance(appearance)
    if let config = try? configBuilder
      .withToken(JXClient.shared.config.onFidoMobileSDKToken)
      .withApplicantId(applicantId)
      .withDocumentStep()
      .build() {
      return config
    }
    return nil
  }

 onfidoFlow = OnfidoFlow(withConfiguration: config)
        .with(responseHandler: { response in
          switch response {
          case let .error(error):
            switch error {
            case OnfidoFlowError.cameraPermission:
              // It happens if the user denies permission to the sdk during the flow
              self.delegate?.cameraAccessDenied()
            case OnfidoFlowError.failedToWriteToDisk:
              // It happens when the SDK tries to save capture to disk, maybe due to a lack of space
              self.delegate?.flowFailed(error: "Disk space full")
            case OnfidoFlowError.microphonePermission:
            // It happens when the user denies permission for microphone usage by the app during the flow
              self.delegate?.microphoneAccessDenied()
            case OnfidoFlowError.upload(let onfidoApiError):
            // It happens when the SDK receives an error from a API call see [https://documentation.onfido.com/#errors](https://documentation.onfido.com/#errors) for more information
              self.delegate?.flowFailed(error: onfidoApiError.description)
            case OnfidoFlowError.exception(withError: let error, withMessage: _):
            // It happens when an unexpected error occurs, please contact [ios-sdk@onfido.com](mailto:ios-sdk@onfido.com?Subject=ISSUE%3A) when this happens
              self.delegate?.flowFailed(error: error?.localizedDescription ?? "Unknown error")
            default: // necessary because swift
              self.delegate?.flowFailed(error: "Unknown error")
            }
          case let .success(results):
            // User completed the flow
          // You can create your check here
            self.delegate?.flowFinished(results: results)
          case .cancel:
            // Flow cancelled by the user
            self.delegate?.flowCancelled()
          }
        })
`

### Steps to reproduce:
Scan ID flow:
Select a document screen:
1 -  tap on 'Driver's License' 
* Select your country screen:
2 - tap on 'Can't find your country?'
* nothing happens

**Comment by anuragajwani** [comment] 2019-04-04 14:57
Hi @VladStrigunov,

I have checked the behaviour and it is working as expected. When you tap on "Can't find your country" the view should slide up. You can then slide down the view by tapping close. Tapping again on "Can't find your country whilst the whole of the view is visible shouldn't do anything. The other option is "Select another document" which should take you back to the document type selection screen.

From Steps to reproduce:

1 - tap on 'Driver's License'
Select your country screen:
2 - tap on 'Can't find your country?'
nothing happens -> *slides up can't find your country view*

tested on iPhone X iOS 12.2 simulator

Let me know if you are experiencing a different behaviour please or it is consistent to my description above so I can close this issue,
Anurag

**Comment by VladStrigunov** [comment] 2019-04-04 18:23
Hi @anuragajwani,
Behavior that I described is consistent 

(When user taps on 'Can't find your country?' prompt is not displayed.
'Can't find your country?' is not clickable.)

We tested it on real devices, from iPhone 6 to XS, iOS 12.2

**Comment by VladStrigunov** [comment] 2019-04-14 17:56
@anuragajwani can we provide any more info to try and resolve the issue?

**Comment by bartzet** [comment] 2019-04-15 07:58
Morning @VladStrigunov. We have released the Version 11.0.1 last week (https://github.com/onfido/onfido-ios-sdk/releases/tag/11.0.1)

Could you please try with that version and let us know whether you still experience the issue? 
Thanks,
Bart

**Comment by anuragajwani** [comment] 2019-04-15 15:12
@VladStrigunov could you share a test project where you can consistently reproduce the error please?

**Comment by VladStrigunov** [comment] 2019-04-19 18:40
@anuragajwani we will set up a test project and share it next week. In the meantime adding video of the issue reproduction. 
I'm tapping the link about 5 times on the video. https://drive.google.com/open?id=1IasWSbMiMRV0BiM0Oi7r1mkqiK0tCC0J

**Comment by anuragajwani** [comment] 2019-04-19 18:49
@VladStrigunov I have requested access to the file

**Comment by keremgund** [comment] 2019-07-22 15:30
Hi @VladStrigunov, have you tried latest SDK version and check whether the issue still exists ?
If it still exists, then please give us access to open your google drive link, we don't have permission at the moment. You can use kerem.gunduz@onfido.com to give permission.

Thanks,
Kerem

**Comment by keremgund** [comment] 2019-09-09 15:17
Closing this task due to lack of response. 
Please open new ticket if you need further support.

**Closed by keremgund** 2019-09-09 15:17 UTC
Labels: awaiting response, unable to reproduce, user
