### ISSUE TITLE
Failed to send selfie capture and complete identity verification from Simulator on version 17.0.0

### ISSUE THREAD

**Issue by fmessina** [onfido/onfido-ios-sdk#146] opened 2020-03-06 21:23 UTC
### What was the expected behaviour?

On version 17.0.0, running from simulator (on sandbox enviroment), Onfido SDK should have let me complete identity verification after an empty (black) selfie capture.

### What happened instead?

The "No face found" error is presented repeatedly, without the possibility to complete identity verification from the simulator.
In prior versions, after retrying once the selfie verification, even from simulator, it would succeed.

### Version info:

- Cocoapods (if applicable):
- Onfido SDK (Debug/Release): Debug
- iOS: 13.2.2
- Xcode: 11.2.1
- Device/Simulator: Simulator
- Device/Simulator language: English

### Steps to reproduce:
- Setup the configuration with the building step
```
            .withFaceStep(ofVariant: .photo(withConfiguration: nil))
``` 
- launch the identity verification from simulator
- provide an empty document (i.e. passport). after a first retry, the sdk allows to proceed to the next step
- take an empty (black) selfie. before version 17.0.0, after a first retry, the sdk would allow to proceed. now it is not possible anymore.

**Comment by nfb-engineering** [comment] 2020-03-13 09:20
I am also experiencing the same issue. I am running detox end-to-end tests on an iOS simulator which fail at the selfie stage of the Onfido journey. This is due to the fact that Onfido is now running selfie capture validation on the device instead of back-end. Would it be possible to disable this new feature if using a simulator?

**Comment by walterholohan** [comment] 2020-03-13 09:20
I am also experiencing the same issue. I am running detox end-to-end tests on an iOS simulator which fail at the selfie stage of the Onfido journey. This is due to the fact that Onfido is now running selfie capture validation on the device instead of back-end. Would it be possible to disable this new feature if using a simulator?

**Comment by seewah** [comment] 2020-03-13 15:32
indeed. we have recently added face detection on the selfie confirmation screen. Are you use an actual photo with a human face (any would do) for testing, or is that not possible with your setup? Thanks

**Comment by tombarton** [comment] 2020-03-13 15:37
The issue is how you run Onfido in a simulator post 17.0.0 as we have no access to the camera in the simulator to display a photo of a human face:

https://help.apple.com/simulator/mac/current/#/devb0244142d

**Comment by seewah** [comment] 2020-03-13 16:38
thanks I will talk to our iOS engineers and see what we can do to enable your testing. apologies for the inconvenience

**Comment by tombarton** [comment] 2020-03-13 16:52
Thanks @seewah! Sorry if that comment seemed grumpy :)

**Comment by anuragajwani** [comment] 2020-03-16 14:53
@tombarton, @walterholohan, @fmessina 

do you do UI testing on real devices?

**Comment by fmessina** [comment] 2020-03-16 15:35
we do UI Testing on simulator, but also use real devices for manual QA testing.
Also, we rely on simulators a lot during development, and our "signup" process has an "onfido" mandatory step (on onfido sandbox)

**Comment by walterholohan** [comment] 2020-03-16 15:36
Same as @fmessina

**Comment by keremgund** [comment] 2020-03-17 12:10
Hello @tombarton, @walterholohan, @fmessina,
Thanks for reporting the issue. 
We're working on the fix now and will publish it as soon as possible. I will let you know from here once we release it.

Sorry for the inconvenience,
Kerem

**Comment by keremgund** [comment] 2020-04-20 17:02
Hello @tombarton, @walterholohan, @fmessina,
I'm glad to say that we have just released 18.0.0 version which contains fix for this problem.
Please check it out and let us know about the result.

Thank you for your patience,
Kerem

**Comment by keremgund** [comment] 2020-04-27 15:03
Closing the issue as we have released version which resolves this problem.
Please open new one if you think that the issue still persists.

Thanks,
Kerem

**Closed by keremgund** 2020-04-27 15:03 UTC
Labels: awaiting response, integrator

**Comment by zvjerka24** [comment] 2022-05-18 13:52
Until recently, we were using version 18.0.0. 

We have updated to 25.0.0 and now we are unable to proceed further than document upload step (it fails here with OnfidoFlowError - validation_error - "There was a validation error on this request" - "has contents that are not what they are reported to be"), because taken photo is "black". Seems like additional checks are done on your backend.

Because of this our UI tests can't pass further.
