### ISSUE TITLE
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib Xcode 12 iOS 14

### ISSUE THREAD

**Issue by stringcode86** [onfido/onfido-ios-sdk#180] opened 2020-09-15 15:16 UTC
### What was the expected behaviour?

App not crashing at launch

### What happened instead?

App crashed on launch

### Version info:

- Cocoapods (if applicable): 1.5.3
- Onfido SDK (Debug/Release): 17.0.0
- iOS: 14.0
- Xcode: 12 Beta 6
- Device/Simulator: iPhone 8 Simulator
- Device/Simulator language: English

### Integration configuration:

Please add code snippet(s) of your integration with the Onfido SDK and all customisations of it.

### Steps to reproduce:

- manually delete derived data
- clean in Xcode
App will crash during the link phase when building with Xcode 12, for iOS 14 simulator

```
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
 Referenced from: /Users/julia/Library/Developer/CoreSimulator/Devices/4717C7E2-DD17-413C-9E35-EABD1138A965/data/Containers/Bundle/Application/93097D28-CCEC-4A37-962C-1B0DB2525145/MyApp.app/Frameworks/Onfido.framework/Onfido
 Reason: no suitable image found.  Did find:
	/usr/lib/swift/libswiftAVFoundation.dylib: mach-o, but not built for platform iOS-sim
dyld: launch, loading dependent libraries
DYLD_SHARED_CACHE_DIR=/Users/julia/Library/Developer/CoreSimulator/Caches/dyld/19F101/com.apple.CoreSimulator.SimRuntime.iOS-14-0.18A5357e
DYLD_ROOT_PATH=/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
DYLD_LIBRARY_PATH=/Users/julia/Library/Developer/Xcode/DerivedData/MyApp-geuxjkqprcgpakfrrvueyxjxwmei/Build/Products/Debug-Daily-watchsimulator:/Users/julia/Library/Developer/Xcode/DerivedData/MyApp-geuxjkqprcgpakfrrvueyxjxwmei/Build/Products/Debug-Daily-iphonesimulator:/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/R
(lldb) 
```

Given the GM is dropping tonight, I was planing to submit my iOS 14 version of the app tonight. Not exactly thrilled about not being able to due to Onfido SDK. Please help

**Comment by michaelmapper** [comment] 2020-09-15 15:30
I am having same issue. Adding `libSwiftAVFoundation.tbd` does not solve the issue when compiling for iOS 14 with Xcode 12. GM dropping tonight, is there any workaround or ETA when is this going to be fixed ?

**Comment by melvinwijenayaka** [comment] 2020-09-16 13:55
I also have the same issue

**Comment by anuragajwani** [comment] 2020-09-16 15:28
Hi @stringcode86, @michaelmapper, @melvinwijenayaka 

I am able to reproduce the issue. I will update you once I understand what's causing the issue. 

Sorry for the inconvenience caused,
Anurag

**Comment by adamwaite** [comment] 2020-09-17 07:17
Receiving the same issue in Xcode 12 GM, but only in the unit test targets.

```
  Assertions: System: Failed to load the test bundle. If you believe this error represents a bug, please attach the result bundle at /Users/adamwaite/Library/Developer/Xcode/DerivedData/Chip-emfdkwnfwifrmrgjpswbryxnokcr/Logs/Test/Test-Chip-2020.09.17_08-02-12-+0100.xcresult. (Underlying Error: The bundle “OnboardingTests” couldn’t be loaded because it is damaged or missing necessary resources. The bundle is damaged or missing necessary resources. Try reinstalling the bundle. dlopen_preflight(/Users/adamwaite/Library/Developer/Xcode/DerivedData/Chip-emfdkwnfwifrmrgjpswbryxnokcr/Build/Products/Debug-iphonesimulator/OnboardingTests.xctest/OnboardingTests): Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /Users/adamwaite/Library/Developer/Xcode/DerivedData/Chip-emfdkwnfwifrmrgjpswbryxnokcr/Build/Products/Debug-iphonesimulator/OnboardingTests.xctest/Frameworks/Onfido.framework/Onfido
  Reason: no suitable image found.  Did find:
	/usr/lib/swift/libswiftAVFoundation.dylib: mach-o, but not built for platform iOS-sim
	/usr/lib/swift/libswiftAVFoundation.dylib: mach-o, but not built for platform iOS-sim)
```

**Comment by Bardiamist** [comment] 2020-09-17 08:33
Steps to reproduce:
1. Create iOS project
2. Add Podfile
```
platform :ios, '10.0'
use_frameworks!

target 'onf' do
  pod 'Onfido', '18.4.0'
end
```
I tried also `18.3.3`, `18.3.0`, `18.2.0`, `18.1.0`, `18.0.0`, `17.0.0`, `16.0.0`.
3. `pod install`

Result: app crahs on launch.

It worked fine on `Xcode 12 beta 5`. But crash on `Xcode 12 beta 6` and on stable `Xcode 12`.
macOS: Catalina 10.15.6
CocoaPods: 1.9.3

<details>
  <summary>Screenshot</summary>
  
![Uploading Screenshot 2020-09-17 at 15.32.26.png…]()

</details>

**Comment by JackTudor96** [comment] 2020-09-17 09:12
Also experiencing this same issue

**Comment by mknabbe** [comment] 2020-09-17 12:39
Issue appears only when I build for simulator with Xcode 12.0 beta 6 and GM, building for a connected device works fine.
Xcode 12.0 beta 6 (12A8189n) and Xcode 12.0 (12A7209)
CocoaPods 1.8.4
Onfido SDK 18.3.0

**Comment by adamivancza** [comment] 2020-09-17 14:29
It seems to be affecting iOS 14 simulators only - I was able to run it on an iOS 12 simulator using Xcode 12.

**Comment by alvarhansen** [comment] 2020-09-18 14:08
In case it helps someone: It seems that in Xcode 12 GM (and 12.2 Beta) `libswiftAVFoundation.tbd` is missing from iOS 14 iPhoneSimulator SDK. But its there for iPhoneOS SDK. 

```` sh
ls -1 /Users/alvarhansen/Downloads/Xcode_12_GM.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/swift/
ARKit.swiftmodule
AVFoundation.swiftmodule
Accelerate.swiftmodule
AppleArchive.swiftmodule
AssetsLibrary.swiftmodule
CallKit.swiftmodule
CloudKit.swiftmodule
Compression.swiftmodule
Contacts.swiftmodule
CoreAudio.swiftmodule
CoreData.swiftmodule
CoreFoundation.swiftmodule
CoreGraphics.swiftmodule
CoreImage.swiftmodule
CoreLocation.swiftmodule
CoreMIDI.swiftmodule
CoreML.swiftmodule
CoreMedia.swiftmodule
CoreNFC.swiftmodule
CryptoTokenKit.swiftmodule
Darwin.swiftmodule
Dispatch.swiftmodule
Foundation.swiftmodule
GLKit.swiftmodule
GameplayKit.swiftmodule
HealthKit.swiftmodule
HomeKit.swiftmodule
Intents.swiftmodule
MLCompute.swiftmodule
MapKit.swiftmodule
MediaPlayer.swiftmodule
Metal.swiftmodule
MetalKit.swiftmodule
MetricKit.swiftmodule
ModelIO.swiftmodule
NaturalLanguage.swiftmodule
NearbyInteraction.swiftmodule
Network.swiftmodule
ObjectiveC.swiftmodule
PencilKit.swiftmodule
Photos.swiftmodule
PhotosUI.swiftmodule
QuartzCore.swiftmodule
SceneKit.swiftmodule
Speech.swiftmodule
SpriteKit.swiftmodule
Swift.swiftmodule
SwiftOnoneSupport.swiftmodule
System.swiftcrossimport
System.swiftmodule
UIKit.swiftmodule
UniformTypeIdentifiers.swiftmodule
Vision.swiftmodule
WebKit.swiftmodule
XCTest.swiftmodule
_System_Foundation.swiftmodule
libswiftARKit.tbd
libswiftAVFoundation.tbd
libswiftAccelerate.tbd
libswiftAppleArchive.tbd
libswiftAssetsLibrary.tbd
libswiftCallKit.tbd
libswiftCloudKit.tbd
libswiftCompression.tbd
libswiftContacts.tbd
libswiftCore.tbd
libswiftCoreAudio.tbd
libswiftCoreData.tbd
libswiftCoreFoundation.tbd
libswiftCoreGraphics.tbd
libswiftCoreImage.tbd
libswiftCoreLocation.tbd
libswiftCoreMIDI.tbd
libswiftCoreML.tbd
libswiftCoreMedia.tbd
libswiftCoreNFC.tbd
libswiftCryptoTokenKit.tbd
libswiftDarwin.tbd
libswiftDemangle.tbd
libswiftDispatch.tbd
libswiftFoundation.tbd
libswiftGLKit.tbd
libswiftGameplayKit.tbd
libswiftHealthKit.tbd
libswiftHomeKit.tbd
libswiftIntents.tbd
libswiftMLCompute.tbd
libswiftMapKit.tbd
libswiftMediaPlayer.tbd
libswiftMetal.tbd
libswiftMetalKit.tbd
libswiftMetricKit.tbd
libswiftModelIO.tbd
libswiftNaturalLanguage.tbd
libswiftNearbyInteraction.tbd
libswiftNetwork.tbd
libswiftObjectiveC.tbd
libswiftPencilKit.tbd
libswiftPhotos.tbd
libswiftPhotosUI.tbd
libswiftQuartzCore.tbd
libswiftSceneKit.tbd
libswiftSpeech.tbd
libswiftSpriteKit.tbd
libswiftSwiftOnoneSupport.tbd
libswiftSystem.tbd
libswiftSystem_Foundation.tbd
libswiftUIKit.tbd
libswiftUniformTypeIdentifiers.tbd
libswiftVision.tbd
libswiftWebKit.tbd
libswiftXCTest.tbd
libswiftos.tbd
libswiftsimd.tbd
os.swiftmodule
shims
simd.swiftmodule
````

```
ls -1 /Users/alvarhansen/Downloads/Xcode_12_GM.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/lib/swift/
ARKit.swiftmodule
AVFoundation.swiftmodule
Accelerate.swiftmodule
AppleArchive.swiftmodule
AssetsLibrary.swiftmodule
CallKit.swiftmodule
CloudKit.swiftmodule
Compression.swiftmodule
Contacts.swiftmodule
CoreAudio.swiftmodule
CoreData.swiftmodule
CoreFoundation.swiftmodule
CoreGraphics.swiftmodule
CoreImage.swiftmodule
CoreLocation.swiftmodule
CoreMIDI.swiftmodule
CoreML.swiftmodule
CoreMedia.swiftmodule
CoreNFC.swiftmodule
CryptoTokenKit.swiftmodule
Darwin.swiftmodule
Dispatch.swiftmodule
Foundation.swiftmodule
GLKit.swiftmodule
GameplayKit.swiftmodule
HealthKit.swiftmodule
HomeKit.swiftmodule
Intents.swiftmodule
MLCompute.swiftmodule
MapKit.swiftmodule
MediaPlayer.swiftmodule
Metal.swiftmodule
MetalKit.swiftmodule
MetricKit.swiftmodule
ModelIO.swiftmodule
NaturalLanguage.swiftmodule
NearbyInteraction.swiftmodule
Network.swiftmodule
ObjectiveC.swiftmodule
PencilKit.swiftmodule
Photos.swiftmodule
PhotosUI.swiftmodule
QuartzCore.swiftmodule
SceneKit.swiftmodule
Speech.swiftmodule
SpriteKit.swiftmodule
Swift.swiftmodule
SwiftOnoneSupport.swiftmodule
System.swiftcrossimport
System.swiftmodule
UIKit.swiftmodule
UniformTypeIdentifiers.swiftmodule
Vision.swiftmodule
WebKit.swiftmodule
XCTest.swiftmodule
_System_Foundation.swiftmodule
libswiftARKit.tbd
libswiftAVFoundation.tbd
libswiftAccelerate.tbd
libswiftAppleArchive.tbd
libswiftAssetsLibrary.tbd
libswiftCallKit.tbd
libswiftCloudKit.tbd
libswiftCompression.tbd
libswiftContacts.tbd
libswiftCore.tbd
libswiftCoreAudio.tbd
libswiftCoreData.tbd
libswiftCoreFoundation.tbd
libswiftCoreGraphics.tbd
libswiftCoreImage.tbd
libswiftCoreLocation.tbd
libswiftCoreMIDI.tbd
libswiftCoreML.tbd
libswiftCoreMedia.tbd
libswiftCoreNFC.tbd
libswiftCryptoTokenKit.tbd
libswiftDarwin.tbd
libswiftDemangle.tbd
libswiftDispatch.tbd
libswiftFoundation.tbd
libswiftGLKit.tbd
libswiftGameplayKit.tbd
libswiftHealthKit.tbd
libswiftHomeKit.tbd
libswiftIntents.tbd
libswiftMLCompute.tbd
libswiftMapKit.tbd
libswiftMediaPlayer.tbd
libswiftMetal.tbd
libswiftMetalKit.tbd
libswiftMetricKit.tbd
libswiftModelIO.tbd
libswiftNaturalLanguage.tbd
libswiftNearbyInteraction.tbd
libswiftNetwork.tbd
libswiftObjectiveC.tbd
libswiftPencilKit.tbd
libswiftPhotos.tbd
libswiftPhotosUI.tbd
libswiftQuartzCore.tbd
libswiftSceneKit.tbd
libswiftSpeech.tbd
libswiftSpriteKit.tbd
libswiftSwiftOnoneSupport.tbd
libswiftSystem.tbd
libswiftSystem_Foundation.tbd
libswiftUIKit.tbd
libswiftUniformTypeIdentifiers.tbd
libswiftVision.tbd
libswiftWebKit.tbd
libswiftXCTest.tbd
libswiftos.tbd
libswiftsimd.tbd
os.swiftmodule
shims
simd.swiftmodule
```

**Comment by keremgund** [comment] 2020-09-23 14:29
Hello all,
We've fixed the issue and now we're in the process of releasing it. 
We aim to deliver new release by the end of this week.

Thanks,
Kerem

**Comment by jamesjara** [comment] 2020-09-23 21:53
thanks

**Comment by keremgund** [comment] 2020-09-24 11:58
Hello again,

We've just released `18.6.0` version to fix the issue. Could you please upgrade SDK version and confirm that whether issue disappeared ?

Thanks,
Kerem

**Comment by adamwaite** [comment] 2020-09-24 16:55
I can confirm that the new `18.6.0` pod runs on iOS 14 simulators! Thank you! 

I'm interested to know what the issue was, and how you went about fixing it?

Thanks.

**Comment by mknabbe** [comment] 2020-09-25 07:39
I can build and run my project with version 18.6.0 and Xcode Version 12.0 (12A7209) on iOS 14 simulators too. Thanks a lot :)

**Comment by keremgund** [comment] 2020-09-25 09:31
Thanks for confirming the fix. I'm closing the issue now.
@adamwaite It was about building with Xcode 12.

**Closed by keremgund** 2020-09-25 09:31 UTC
Labels: awaiting response

**Comment by Bardiamist** [comment] 2020-10-08 09:51
@keremgund Problem is back in `18.7.0`.

**Comment by keremgund** [comment] 2020-10-08 12:16
@Bardiamist I've just tested SampleApp with `18.7.0` running on Xcode 12(12A7209) and iPhone 11 14.0 simulator and was able to complete end to end SDK flow without any problem

**Comment by Bardiamist** [comment] 2020-10-08 12:20
Hmm, I checked couple times. Can somebody else confirm?
I use Xcode 12.0.1 (12A7300) and and iPhone 11 14.0 simulator.
Works without problems with `18.6.0`

**Comment by Bardiamist** [comment] 2020-10-08 12:44
@keremgund 
I see it's not exactly same problem.

```
dyld: Library not loaded: /usr/lib/libnfshared.dylib
  Referenced from: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreNFC.framework/CoreNFC
  Reason: no suitable image found.  Did find:
	/usr/lib/libnfshared.dylib: mach-o, but not built for platform iOS-sim
dyld: launch, loading dependent libraries
DYLD_SHARED_CACHE_DIR=/Users/bardiamist/Library/Developer/CoreSimulator/Caches/dyld/19H2/com.apple.CoreSimulator.SimRuntime.iOS-14-0.18A372
DYLD_ROOT_PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot
DYLD_LIBRARY_PATH=/Users/bardiamist/Library/Developer/Xcode/DerivedData/valr-gcfwctharjklzxamsqckslyxgkbd/Build/Products/Debug-iphonesimulator:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libBacktraceRecording.dylib:/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSi
(lldb) 
```

But looks similar. Maybe I'll create new issue for it later then if need.

**Comment by anuragajwani** [comment] 2020-10-08 13:31
@Bardiamist this is known Xcode issue. We have shared the warning on the [README](https://github.com/onfido/onfido-ios-sdk#getting-started) and [MIRGATION](https://github.com/onfido/onfido-ios-sdk/blob/master/MIGRATION.md#onfido-ios-sdk-1870-migration-guide) docs.

You can also read more about the problem and solve it using the response offered in [stackoverflow](https://stackoverflow.com/questions/63915728/xcode12-corenfc-simulator-library-not-loaded)

**Comment by Bardiamist** [comment] 2020-10-09 04:13
@anuragajwani Ok, thanks:)
Would be good to add things related with migration to release notes here https://github.com/onfido/onfido-ios-sdk/releases/tag/18.7.0
