### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by iangmaia** [onfido/onfido-ios-sdk#100] opened 2019-07-01 15:24 UTC
Onfido should add support to Carthage, as requested previously.
I'm re-adding this issue since the [previous one](https://github.com/onfido/onfido-ios-sdk/issues/44) was closed.

**Comment by anuragajwani** [comment] 2019-07-08 15:48
Apologies @iangmaia we have closed the issue by mistake

**Comment by alvarhansen** [comment] 2019-08-30 04:45
@iangmaia you can do this with local Spec file like so:

`Onfido.json`
```
{
  "12.0.0": "https://github.com/onfido/onfido-ios-sdk/releases/download/12.0.0/Onfido-Debug-v12.0.0.zip"
}
```

And then, in Cartfile, point to this json file like so:
```
binary "Onfido.json" == 12.0.0
```

**Comment by iangmaia** [comment] 2019-08-30 08:08
Hi @alvarhansen,  I have been doing this to workaround the issue for now, but then that also implies in using the Debug binaries.

The problem is that the `Release` ones don't include binaries for simulator, which prevents a proper development flow using Carthage.

Any updates on this issue @anuragajwani ?

**Comment by alvarhansen** [comment] 2019-08-30 09:06
@iangmaia "Onfido-Debug" contains Release slices for arm architectures and Debug only for simulator. (@anuragajwani can confirm since which version this started)

**Comment by anuragajwani** [comment] 2019-09-03 19:22
Hi @iangmaia @alvarhansen,

`Onfido-Debug` has been containing release slices for devices since 11.1.0. `Onfido-Release` has been deprecated since [then](https://github.com/onfido/onfido-ios-sdk/blob/master/MIGRATION.md#onfido-ios-sdk-1110-migration-guide). We have continued to support it to allow for integrators to migrate to the single framework.

From version 14.0.0-beta we are no longer supporting `Onfido-Release`.

Anurag

**Comment by iangmaia** [comment] 2019-09-04 08:16
Hi @anuragajwani, this is good news, thanks!

**Comment by keremgund** [comment] 2019-10-07 15:58
There is good news ! 
We just started to support Carthage with our latest [release](https://github.com/onfido/onfido-ios-sdk/releases/tag/14.0.0).
Please check our [README](https://github.com/onfido/onfido-ios-sdk#using-carthage) for the instructions about how to use it.

If you have any question/problem about the integration please let us know.

Thanks,
Kerem

**Comment by alvarhansen** [comment] 2019-10-08 11:04
@keremgund Could you rename the spec file to `Onfido.json` or something simila. `carthage-spec.json`is very ambigious and can cause issues because this JSON file name is used and dependency name.
When updating single dependency, for Onfido I have to run this command: `carthage update carthage-spec`

Example of Carthage output:
```
*** No cache found for carthage-spec, building with all downstream dependencies
*** Downloading binary-only framework carthage-spec at "https://raw.githubusercontent.com/onfido/onfido-ios-sdk/master/carthage-spec.json"
*** xcodebuild output can be found in /var/folders/jk/w5g3wmmj197852wb7t52vbp80000gp/T/carthage-xcodebuild.lZNkIm.log
*** Downloading carthage-spec.framework binary at "14.0.0"
```

**Comment by keremgund** [comment] 2019-10-08 16:22
Hello @alvarhansen, as full url will be used to identify dependency I didn't understand why it might cause a problem. I got that during the `carthage update` operation it says `carthage-spec` in console but there is also url information just next to that.

It would be good to hear more details from you about why it's necessary to change file name.

Thanks,
Kerem

**Comment by alvarhansen** [comment] 2019-10-09 04:35
@keremgund never mind. I was under impression, that it will cause conflicts if there are multiple specs with same name, but it seems not to be an issue after-all.

But it will cause issues with Rome as you need to map the spec file name framework name: https://github.com/tmspzz/Rome#repositorymap And if you have 2 specs with same name 🤷‍♂

**Comment by keremgund** [comment] 2019-10-09 16:12
Hi @alvarhansen , we will deliver new version with renaming json file to `onfido-carthage-spec.json`. I will let you know from here once we released it.

Thanks,
Kerem

**Comment by keremgund** [comment] 2019-11-05 16:25
Hi all, I want to let you know that 15.0.0 version has been released. Starting with the 15.0.0 version, we started to use onfido-carthage-spec.json file for the carthage support.

Thanks,
Kerem

**Comment by keremgund** [comment] 2019-11-13 16:23
Closing the task as carthage support has been added.
Please open new ticket if you have problem about integrating your application through the carthage. 

Thanks,
Kerem

**Closed by keremgund** 2019-11-13 16:23 UTC
Labels: awaiting response, enhancement, integrator
