### ISSUE TITLE
Swift 5.1 support

### ISSUE THREAD

**Issue by sphw** [onfido/onfido-ios-sdk#98] opened 2019-06-07 22:59 UTC
### What was the expected behaviour?

For the Onfido SDK to compile

### What happened instead?

The app fails to compile because the Onfido SDK was distributed as a framework and not source packages

`Module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler`

It would be helpful if you guys could release a version of the framework built with Xcode 11

### Version info:

- Cocoapods (if applicable):
- Onfido SDK (Debug/Release):
- iOS: 13
- Xcode: 11
- Device/Simulator:
- Device/Simulator language:

### Steps to reproduce:

Built an app using the Onfido SDK with Xcode 11

**Comment by anuragajwani** [comment] 2019-06-10 15:16
Hi @sphw,

Thanks for reporting the issue. We are looking into supporting Xcode 11 builds. We will update you with more information as soon as we have some news.

Thanks,
Anurag

**Comment by JackTudor96** [comment] 2019-07-17 09:33
Any update on when we might have this?

**Comment by keremgund** [comment] 2019-08-07 16:28
Hi @JackTudor96, first of all sorry for the late reply.
We have a plan to release new version of SDK which will be compatible with Xcode 11 Beta before end of August. 
That version will be for our customers to test their app building with Xcode11. 
I will let you know here once we release it.

Thanks,
Kerem

**Comment by anuragajwani** [comment] 2019-09-02 14:16
@JackTudor96 @sphw,

We have release Onfido iOS SDK 14.0.0-beta. The framework was build using Xcode 11 beta 7. If you'd like to use Onfido SDK with Xcode 11 beta 7 please use that version.

Please let us know if you encounter any problems.

Anurag

**Comment by dynbit** [comment] 2019-09-09 10:51
@anuragajwani seems that `Version 14.0.0-beta` of `Onfido.framework` does not have version for simulator (x86_64 arch)

**Comment by anuragajwani** [comment] 2019-09-09 15:09
Hi @dynbit 

I have checked the slices inside the Onfido 14.0.0-beta. It seems like it has the simulator slices.

```
➜  Onfido-14-beta file Onfido.framework/Onfido
Onfido.framework/Onfido: Mach-O universal binary with 4 architectures: [i386:Mach-O dynamically linked shared library i386] [arm64]
Onfido.framework/Onfido (for architecture i386):	Mach-O dynamically linked shared library i386
Onfido.framework/Onfido (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
Onfido.framework/Onfido (for architecture armv7):	Mach-O dynamically linked shared library arm_v7
Onfido.framework/Onfido (for architecture arm64):	Mach-O 64-bit dynamically linked shared library arm64
```

Here are the steps I followed to investigate:
[onfido-14-beta-log.txt](https://github.com/onfido/onfido-ios-sdk/files/3591195/onfido-14-beta-log.txt)

Anurag

**Comment by dynbit** [comment] 2019-09-09 18:29
@anuragajwani thanks! Will investigate why I got that error, will let you know if I will discover something

**Comment by kuzdu** [comment] 2019-09-10 08:08
I ran into the same issue. The problem is that XCode11 use the XCode10 Toolchain. However, you can switch the toolchain very easily. Have look at this post: https://stackoverflow.com/a/56614038/4420355

```XCode -> Preferences -> Locations -> Command Line Tools -> choose XCode 11.0 (xxxxx)```

Please make sure you use minimum iOS 10 in your Podfile
`platform :ios, '10.0'`
And you have specify your onfido version: `pod 'Onfido', '14.0.0-beta'`

**Comment by rresma2** [comment] 2019-09-13 20:32
@anuragajwani 

The above steps work fine for me on Xcode 11, but seems like `14.0.0-beta` isn't backwards compatible with the Swift 5.0.1 compiler. Now I'm getting:

`Module compiled with Swift 5.1 cannot be imported by the Swift 5.0.1 compiler`

Any workaround besides the following steps:

1. Remove `~ 14.0.0` from our Podfile
2. Run `pod install`
3. Build project

I cleaned my build folder and cleared derived data, and switched to using the Xcode 10 toolchain, but I'm still getting the error.

**Comment by keremgund** [comment] 2019-09-16 15:34
Hi @rresma2 , that's the expected behaviour as there is no full ABI compatibility in Swift yet.
So if you want to use Swift 5.0.1, you should downgrade SDK version to 13.2.0 which is latest SDK version supports Swift 5.0.1. However, if you're ready to migrate Swift 5.1, we have released 14.0.0-rc version which is compatible with Xcode11 GM.

**Comment by rresma2** [comment] 2019-09-17 23:40
I'm wondering if it would be possible to add Swift 5.1 support to Onfido-Release. Compiling and running works for us in debug mode, but generating Production and Ad Hoc builds doesn't work because those are using the Onfido-Release pod instead of the Onfido one, which only runs on Swift 5

**Comment by anuragajwani** [comment] 2019-09-18 15:14
Hi @rresma2,

Since [11.1.0](https://github.com/onfido/onfido-ios-sdk/blob/master/MIGRATION.md#onfido-ios-sdk-1110-migration-guide) `Onfido-Release` is deprecated and since [14.0.0-beta](https://github.com/onfido/onfido-ios-sdk/blob/master/MIGRATION.md#onfido-ios-sdk-1400-beta-migration-guide) is no longer supported. We have moved `Onfido-Debug` and `Onfido-Release` to a single framework `Onfido`.

Anurag

**Comment by anuragajwani** [comment] 2019-09-18 15:38
closing ticket as Onfido SDK 14.0.0-rc is compatible with Swift 5.1 in Xcode 11 GM

**Closed by anuragajwani** 2019-09-18 15:38 UTC
Labels: enhancement, integrator
