### ISSUE TITLE
VIDEO_FACIAL_CAPTURE_CONFIRMATION after success

### ISSUE THREAD

**Issue by iuriimoz** [onfido/onfido-ios-sdk#167] opened 2020-07-07 00:18 UTC
### What was the expected behavior?

After configuration
`OnfidoFlow(withConfiguration: config).with(eventHandler: { event in ... }`
The event handler should be called with correct events.

### What happened instead?

Event with screen `VIDEO_FACIAL_CAPTURE_CONFIRMATION` is fired twice:
1) During video facial capture (expected)
2) After end of Onfido flow

### Version info:
- Onfido SDK (Debug/Release): 18.2.0
- iOS: 13.3.1
- Xcode: 11.3.1
- Device/Simulator: Device
- Device/Simulator language: English

### Integration configuration:

    let onfidoConfig = OnfidoConfig.builder()
        .withSDKToken(sdkToken)
        .withDocumentStep(ofType: DocumentType.passport(config: nil))
        .withFaceStep(ofVariant: .video(withConfiguration: nil))
        .withCustomLocalization()
        .withAppearance(appearance)
        .build()

    let onfidoFlow = OnfidoFlow(withConfiguration: onfidoConfig)
        .with(responseHandler: { response in
            OnfidoAnalytics.handleResponse(response)
            responseHandler(response)
        }, dismissFlowOnCompletion: dismissFlowOnCompletion)
        .with { event in
            OnfidoAnalytics.handleEvent(event)
    }

### Steps to reproduce:

1) Start Onfido flow
2) Finish document capture
3) Go through video facial capture
4) Inspect `VIDEO_FACIAL_CAPTURE_CONFIRMATION` event
5) Upload video and finish flow
6) `VIDEO_FACIAL_CAPTURE_CONFIRMATION` is received for 2nd time

**Comment by anuragajwani** [comment] 2020-07-08 15:11
Hi @iuriimoz 

I'll take a look at this now. I will get back to you when I have more information.

Anurag

**Comment by anuragajwani** [comment] 2020-07-08 16:49
HI @iuriimoz I can confirm that I get two `VIDEO_FACIAL_CAPTURE_CONFIRMATION`. I will open a ticket and let you know once this issue has been addressed.

Sorry for the inconvenience caused,
Anurag

**Comment by anuragajwani** [comment] 2020-07-27 16:08
Hi @iuriimoz 

we have issued a fix for this issue in version 18.3.1. Please let us know if you encounter any further issues.

**Comment by keremgund** [comment] 2020-09-01 07:32
Closing the issue due to lack of response. Please open new one if your problem persists.

**Closed by keremgund** 2020-09-01 07:32 UTC
Labels: awaiting response
