### ISSUE TITLE
Crash when you tap on two buttons at the same time

### ISSUE THREAD

**Issue by Mmantass** [onfido/onfido-ios-sdk#68] opened 2019-02-01 11:51 UTC
### What was the expected behaviour?

When you tap on two buttons at the same time only one button should be taped or nothing should happen.

### What happened instead?

Crash after you tap two buttons at the same time.

### Version info:

- Cocoapods: Onfido 10.1
- Onfido SDK Debug
- iOS: this issue is reproducible on all iOS versions
- Xcode: 10.1
- Device/Simulator: this issue is reproducible on all iOS devices or simulators
- Device/Simulator language: English

### Integration configuration:

OnfidoConfig.builder()
  .withToken(Const.mobileSDKToken)
  .withApplicantId(applicantID)
  .withDocumentStep(ofType: onfidoType, andCountryCode: countryCode)
  .withCustomLocalization()
  .withFaceStep(ofVariant: .photo)

### Steps to reproduce:

1.Select any document type (e.g. "National ID card").
2.Make a picture.
3.Tap on "My card is readable" and "Take a new picture"  buttons at the same time with two fingers
4.Hold fingers about 2-3sec.
After these steps app crashes.

I can reproduce this issue on the "Onfido" app as well.

**Comment by anuragajwani** [comment] 2019-02-07 17:41
@Mmantass fyi the issue was not fixed in 10.4.0 as this release was already under way

**Comment by keremgund** [comment] 2019-05-20 16:26
Hi @Mmantass , first of all sorry for the delay in replying. 
I'm glad to say that we were able to reproduce the issue and will deliver the fix soon.
I'II let you know once we have release for this issue.

Thanks,
Kerem

**Comment by anuragajwani** [comment] 2019-05-29 15:22
Hi @Mmantass,

Our current version of the iOS SDK 11.1.2 includes the fix for this issue. Please let us know whether its fixed so we can close this task.

Anurag

**Comment by keremgund** [comment] 2019-07-01 15:13
Closing this issue due to lack of response, if you think there is still an issue about it, you can open new ticket.

Thanks,
Kerem

**Closed by keremgund** 2019-07-01 15:13 UTC
Labels: awaiting response
