### ISSUE TITLE
Binary incompatible with Xcode 11.2.1 using Carthage

### ISSUE THREAD

**Issue by rafaelescoffier** [onfido/onfido-ios-sdk#124] opened 2019-11-27 11:01 UTC
The latest onfido release is still not compatible with the latest swift version released with Xcode 11.2.1.

So using Carthage, we get this error:

`Incompatible Swift version - framework was built with 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7) and the local version is 5.1.2 (swiftlang-1100.0.278 clang-1100.0.33.9).`

**Comment by anuragajwani** [comment] 2019-11-27 11:02
Which Onfido SDK version are you using?

**Comment by rafaelescoffier** [comment] 2019-11-27 11:02
Hey @anuragajwani thanks for the quick response. The version is 16.0.0

**Comment by anuragajwani** [comment] 2019-11-27 11:03
Also I assume you mean Xcode 11.2.1 instead of 12.2.1. Am I correct?

**Comment by rafaelescoffier** [comment] 2019-11-27 11:04
@anuragajwani That is correct, I will fix this.

**Comment by rafaelescoffier** [comment] 2019-11-27 11:49
@anuragajwani also I think this issue is also on Carthage, that should ignore this version change because of swift module stability.

**Comment by anuragajwani** [comment] 2019-11-27 17:07
Hi @rafaelescoffier 

I will be installing Xcode 11.2.1 and try to reproduce your issue. I will get back to you once I have an update.

Anurag

**Comment by anuragajwani** [comment] 2019-12-09 16:54
Hi @rafaelescoffier 

I am able to reproduce your issue. However installing the framework manually in Xcode I am able to build and run. Since Xcode 11 we have been using Swift module compatibility option to not break integration with newer versions of the Swift compiler.

This seems to be a Carthage issue. I am exploring this further.

Sorry for delay in getting back to you,
Anurag

**Comment by anuragajwani** [comment] 2019-12-09 16:56
@rafaelescoffier 

This issue is already reported to Carthage. 
https://github.com/Carthage/Carthage/issues/2887

**Comment by rafaelescoffier** [comment] 2019-12-12 08:50
@anuragajwani Did you compile your latest release with the new Xcode? If so, can you please make it available on Carthage? Not sure how long will take carthage to release a fix for this issue.

**Comment by bartzet** [comment] 2019-12-12 10:27
Hi @rafaelescoffier.
We have just published `16.1.0` version to Carthage. Could you please confirm this resolved your issue?

**Comment by anuragajwani** [comment] 2019-12-12 10:51
Hi @rafaelescoffier,

We haven't released the latest SDK with Xcode 10.2.x. We used Xcode 10.1. Have you tried the suggested workaround mentioned in the Carthage issue thread?

Anurag

**Comment by rafaelescoffier** [comment] 2019-12-12 10:56
Hi @anuragajwani if you meant this workaround 

> A workaround would be to install an older version of Xcode on your system that uses Swift 5.1 (I believe Xcode 11.1 would work) and use the command line tools from that version of Xcode instead of the command line tools from Xcode 11.2.

It's hard to do that when you have multiple CI machines, as it will be necessary to add this workaround everywhere and not only on personal machines.

For us, I guess the solution will be either carthage fixing this, or you guys eventually release a build compiled with new Xcode. Carthage is taking too long with this already, but unfortunately SwiftPM does not support binary yet, so we can get rid of carthage.

**Comment by anuragajwani** [comment] 2019-12-12 11:54
Hi @rafaelescoffier,

I have spoke to the PM and we will discuss this further internally. We will update you once we can. Thanks for flagging the issue.

**Comment by danu6677** [comment] 2020-01-06 16:33
Any solution for the onside pod ? all I get is 

updateTransactions with auth in pdvTyped: {
  error = timeout;
  message = "The request to the server timed out.";
  status = error;
}

**Comment by anuragajwani** [comment] 2020-01-06 16:59
@danu6677 just to clarify when you say download the SDK manually from the git repo do you mean from our Github repository releases tab ?

**Comment by danu6677** [comment] 2020-01-07 01:50
@anuragajwani yes the onfido.framework

**Comment by danu6677** [comment] 2020-01-09 03:05
The are the steps i followed.
1) Remove the onfido pod from the pod file.
2) Download the onfido.framework file from the [link ](https://github.com/onfido/onfido-ios-sdk/releases/tag/14.0.0-rc)
3)Add it to the project frmaworks,Libraries, and embedded content 
4)Clean the derived data and clean build the app and Run it.

then it throws me the error 

`dyld: Library not loaded: @rpath/Onfido.framework/Onfido
Referenced from: /Users/organization/Library/Developer/CoreSimulator/Devices/070F3A8D-F0D5-4B51-9A39-F83BAEE1388D/data/Containers/Bundle/Application/EB777E0B-2DA6-4121-8AB2-BE407A0B4295/appname.app/appname

Reason: image not found`

**Comment by anuragajwani** [comment] 2020-01-27 16:34
@danu6677 make sure you embed the Onfido framework into your app package

**Comment by anuragajwani** [comment] 2020-02-13 10:48
to the original issue of Carthage not considering module stability:

Good news the feature has now been merged to Carthage repo. https://github.com/Carthage/Carthage/pull/2902

We are awaiting release now.

**Comment by sam-w** [comment] 2020-06-22 08:23
I think this issue can be closed: the problem should now be fixed with the release of Carthage 0.35.0

**Comment by anuragajwani** [comment] 2020-06-22 15:07
thanks @sam-w for letting us know. I will test it out and close the issue once confirmed.

**Comment by anuragajwani** [comment] 2020-06-22 15:33
yepp confirmed its working now

**Closed by anuragajwani** 2020-06-22 15:33 UTC
