### ISSUE TITLE
Support SPM

### ISSUE THREAD

**Issue by iangmaia** [onfido/onfido-ios-sdk#182] opened 2020-09-18 12:28 UTC
Now with Xcode 12 / Swift 5.3, it became feasible to add binary frameworks using SPM, so it would be nice to get support for SPM from the Onfido SDK.

**Comment by andra-radu** [comment] 2020-09-18 12:44
Hi @iangmaia,

Thank you for your feedback. I have forwarded to our Product Manager and we will start working on this next quarter. 

Kind regards, 
Andra

**Comment by ekimia** [comment] 2020-09-18 18:06
@andra-radu possible to get this done sooner than next quarter? Carthage is very buggy with xcode 12, and a lot of us dont want to add a big binary in our apps.

**Comment by andra-radu** [comment] 2020-09-21 10:35
@ekimia I have brought this into our SDK team's attention and will let you know as soon as I will receive an update from them. Kind regards, 
Andra

**Comment by keremgund** [comment] 2020-09-21 16:05
Hi all,
As we have been asked to support Carthage before, we added that almost a year ago. 
Now, SPM is getting more and more popular which can also be seen in this thread. But the thing is Carthage doesn't have xcframework support yet. 
Therefore we're in position where we need to decide either drop Carthage support and add SPM (then we can resupport Carthage once xcframework support added), or wait till Carthage add xcframework and do nothing for SPM. 
Given that even if we drop Carthage suppor, customers can still use older SDK versions with Carthage. So we're closer to the option for dropping Carthage support for now. 
We would like to hear from you about this, you can give 👍  if you're happy with this approach.

Thanks,
Kerem

**Comment by ekimia** [comment] 2020-09-25 19:38
@keremgund given how bad of a state carthage is in right now, I think that's a wise choice.

**Comment by keremgund** [comment] 2020-12-14 17:22
Hello all,
I would like to give you some update as it has been a while since we talk last time. We're actively working on this feature now and our goal is to deliver SPM support by the end of Q1 2021.
I will give you more update when we're about to release.

Thanks,
Kerem

**Comment by shaps80** [comment] 2020-12-16 12:23
This sounds great and thank you for keeping us updated!

**Comment by ekimia** [comment] 2020-12-31 00:27
@keremgund to be frank, it would be appreciated to get this done as soon as you guys can. The M1 chip was introduced a long time ago, and now myself and others are at the point where we have to buy our mobile teams older mac hardware due to your framework not being updated. Please try and get your product manager to understand the full effect this delay has had on your customers.

**Comment by shaps80** [comment] 2021-01-07 11:53
While we wait for this I wonder if it would be simple enough for you to add an XCFramework of the library to the repo? This alone solves the core issues around supporting both Silicon and Intel Macs.

In addition Intercom recently took a similar approach, as such this enabled a separate user to do this:
https://github.com/intercom/intercom-ios/pull/391

Ideally this will be 'official' shortly anyway. Just a thought as this is really problematic, thanks!

**Comment by keremgund** [comment] 2021-01-11 17:42
Hi all,
We're very close to release SPM/xcframework feature. So rather than working on workaround we just want to keep our focus working on feature and deliver it ASAP.

Thank you for your understanding,
Kerem

**Comment by shaps80** [comment] 2021-01-18 15:13
> We're very close to release SPM/xcframework feature. So rather than working on workaround we just want to keep our focus working on feature and deliver it ASAP.

Makes sense, glad to hear its close! Thank you for letting me know!

**Comment by anuragajwani** [comment] 2021-01-18 16:56
Hi all,

We are soon finalising the release. The SDK will be built as XCFramework and distributed through SPM in version 20.0.0. You can already find it in Cocoapods. Documentation and SPM updates to be finalised soon.

Anurag

**Comment by shaps80** [comment] 2021-01-18 18:45
Amazing! This will make things so much cleaner thanks for getting this out 👍

**Comment by anuragajwani** [comment] 2021-01-19 11:51
Hi all,

We have completed the release of 20.0.0 now. Please let us know if you encounter any problems.

Anurag

**Comment by shaps80** [comment] 2021-01-22 10:26
Hmm... so I've grabbed `20.0.1` but I'm seeing a few errors around types:

```swift
OnfidoConfig
OnfidoResponse
OnfidoFlowError
```

No type named `xxx` in module `Onfido`

Any ideas?

**Comment by anuragajwani** [comment] 2021-01-25 15:33
Hi @shaps80 

I just tested it out and I'm not seeing any issues. I have shared the test project. Can you share a test project where I can reproduce the issue please?

[XCFRameworkTest.zip](https://github.com/onfido/onfido-ios-sdk/files/5867613/XCFRameworkTest.zip)

**Comment by shaps80** [comment] 2021-01-25 17:20
Sorry, similar issue. I downloaded a zip version, let SPM resolve and hit build. No other changes. Btw, I'm running on Apple M1 Silicon Mac min.
![Uploading Screenshot 2021-01-25 at 17.19.58.png…]()

**Comment by shaps80** [comment] 2021-01-25 17:26
@anuragajwani  👆

**Comment by anuragajwani** [comment] 2021-01-27 12:35
I see. I am not yet running an M1 based Mac. I'll update you once I have it tested in M1 based Mac.

**Comment by shaps80** [comment] 2021-01-27 12:58
Ok yes please, this would great!

**Comment by anuragajwani** [comment] 2021-01-27 15:32
actually @shaps80 given that this ticket is about supporting SPM which we are now could you open a new ticket related to supporting M1 Macs please?

**Comment by shaps80** [comment] 2021-01-27 21:45
Sure

**Comment by keremgund** [comment] 2021-02-09 14:19
Closing this ticket as SPM support has been released.

**Closed by keremgund** 2021-02-09 14:19 UTC
Labels: awaiting response
