### ISSUE TITLE
Memory leak in Onfido module

### ISSUE THREAD

**Issue by alvarhansen** [onfido/onfido-ios-sdk#140] opened 2020-02-26 06:57 UTC
### What was the expected behaviour?

After dismissing OnfidoFlow, we expect all Onfido related memory to be freed.

### What happened instead?

Using Xcode Memory Graph tool we can see that a lot of Onfido Flow related code is in memory. 
Views, ViewControllers, Coordinators.

### Version info:

- Onfido SDK (Debug/Release): 16.1.0, 16.2.0
- iOS: 13.3
- Xcode: 11.3.1
- Device/Simulator: Both

### Integration configuration:

https://github.com/onfido/onfido-ios-sdk/tree/master/SampleApp

### Steps to reproduce:

Using your own sample app, tap on "Verify me!" and then close the flow.
Doing it multiple times during same session increases leaked objects count reliably.

| | |
|-|-|
|<img width="811" alt="Screenshot 2020-02-26 at 08 50 22" src="https://user-images.githubusercontent.com/482293/75319534-89878780-5875-11ea-926c-fd3a122c6a35.png">|<img width="802" alt="Screenshot 2020-02-26 at 08 55 27" src="https://user-images.githubusercontent.com/482293/75319707-d66b5e00-5875-11ea-8a26-12b2cd624852.png">|

**Comment by anuragajwani** [comment] 2020-02-26 16:56
Hi @alvarhansen 

Thanks for letting us know. We will look into this and will update this issue when we have more info.

Anurag

**Comment by keremgund** [comment] 2020-07-06 07:58
Hi @alvarhansen ,
I want to let you know that we were able to reproduce the problem on our side and started to work on fixing the issue.

Sorry for the late reply, will keep you updated from here.
Kerem

**Comment by anuragajwani** [comment] 2020-07-27 16:10
Hi @alvarhansen 

We have issued a fix for the memory leaks in version 18.3.1. Please let us know if you encounter any further issues. If none encountered please close this ticket.

**Comment by keremgund** [comment] 2020-09-01 07:33
Closing the issue due to lack of response. Please open new one if your problem persists.

**Closed by keremgund** 2020-09-01 07:33 UTC
Labels: awaiting response
