### ISSUE TITLE
AutoLayout Issues: Buttons have different heights 

### ISSUE THREAD

**Issue by clapslock** [onfido/onfido-ios-sdk#169] opened 2020-07-22 12:19 UTC
### What was the expected behaviour?

Both buttons ("Upload photo", "Retake photo") are of the same height.
<img width="600" alt="Screen Shot 2020-07-22 at 11 21 16" src="https://user-images.githubusercontent.com/24473612/88175179-c9387c80-cc25-11ea-9832-c0720410964c.png">

### What happened instead?

Both buttons have different heights. 
Additionally the newest version of your SDK has multiple Layout issues: 

<img width="253" alt="Screen Shot 2020-07-22 at 14 17 32" src="https://user-images.githubusercontent.com/24473612/88175393-174d8000-cc26-11ea-8e4b-abcdb7e39a8c.png">

### Version info:

- Cocoapods (if applicable):
- Onfido SDK (Debug/Release):
- iOS: 13.5
- Xcode: 11.5
- Device/Simulator: iPhone X

### Steps to reproduce:

Just launch your sample app from this repository and start the flow.

**Comment by anuragajwani** [comment] 2020-07-22 14:39
Hi @clapslock 

I was able to reproduce the issue. I have created a ticket internally and will update you once there is some progress.

Sorry for the inconvenience caused

**Comment by anuragajwani** [comment] 2020-08-06 11:14
Hi @clapslock,

The fix for this issue has been released on version [18.3.2](https://github.com/onfido/onfido-ios-sdk/blob/master/CHANGELOG.md#1832---2020-08-06).

**Comment by keremgund** [comment] 2020-09-01 07:33
Closing the issue due to lack of response. Please open new one if your problem persists.

**Closed by keremgund** 2020-09-01 07:33 UTC
Labels: awaiting response
