### ISSUE TITLE
Crash on launch for iOS < 13 compiled with Xcode 11.1

### ISSUE THREAD

**Issue by shaddeen** [onfido/onfido-ios-sdk#118] opened 2019-10-17 10:26 UTC
### What was the expected behaviour?

App launches

### What happened instead?

App crashes.

Logs:

```
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /Users/work/Library/Developer/CoreSimulator/Devices/D1A15C37-8642-44A8-B2D7-4E51FDE1078F/data/Containers/Bundle/Application/F9AA5486-800B-44ED-91EB-2FA4274F7D41/test.app/Frameworks/Onfido.framework/Onfido
  Reason: no suitable image found.  Did find:
	/usr/lib/swift/libswiftAVFoundation.dylib: mach-o, but not built for iOS simulator
	/usr/lib/swift/libswiftAVFoundation.dylib: mach-o, but not built for iOS simulator
```

- Onfido SDK (Debug/Release): Both
- iOS: 11.4
- Xcode: 11.1
- Device/Simulator: Simulator iPhone X
- Carthage: 0.33.0
- Cocoapods: 1.8.4

```
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /private/var/containers/Bundle/Application/74589721-D9FA-4716-B590-F5CBC04114F8/test.app/Frameworks/Onfido.framework/Onfido
  Reason: image not found
```

- Onfido SDK (Debug/Release): Both
- Xcode: 11.1
- Device/Simulator: Device iPhone 6S (iOS 12.1.4), Device iPhone SE (iOS 11.4.1)
- Cocoapods: 1.8.4

### Steps to reproduce:

Build & Run project with spec stated above.

- App compiles but never reaches `didFinishLaunchingWithOptions` when running. Onfido does not need to be imported in any classes either, only the framework linked.

**Comment by anuragajwani** [comment] 2019-10-17 13:55
Hi @shaddeen,

Since Xcode 11 we have been experiencing a similar issue to this. To solve this add `libswiftAVFoundation.tdb` to your `Frameworks, Libraries, and Embedded Content`. You might see similar issues after adding the framework for other frameworks, i.e. CoreMedia. Please apply the same solution for those (`libswiftCoreMedia.tbd`).

Here are the other issues in our Github which were solved:
- https://github.com/onfido/onfido-ios-sdk/issues/117
- https://github.com/onfido/onfido-ios-sdk/issues/115

Please let me know if this solves your problem.

Sorry for the inconvenience,
Anurag

**Comment by shaddeen** [comment] 2019-10-17 16:02
Thanks, this does solve the problem for now but is obviously not ideal. Is there any further progress with a full solution?

**Comment by anuragajwani** [comment] 2019-10-21 15:25
I believe this is an Xcode related problem. I am unable to reproduce this issue using our SampleApp located inside this repository using Xcode 11.1.

The problem might be related to:
```
Command Line Tools
Known Issues
When using the Command Line Tools as the active Developer directory, some users may experience random crashes in the Swift compiler. (53582696)
Workaround: Execute the command sudo rm -f /Library/Developer/CommandLineTools/usr/lib/swift/macosx/libswift*.dylib in Terminal.
```

You can find the known issue in the [Xcode 11 release notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_release_notes)

However given that I haven't experienced the issue myself first hand I am unable to say the above solution will work. Also given the uncertainty of the problem there is no further progress for a solution to this problem yet.

Anurag

**Comment by shaddeen** [comment] 2019-10-22 14:09
I'm happy to create a branch with a sample project I have that carries this issue if that would help?

**Comment by anuragajwani** [comment] 2019-10-23 15:43
That might help for us to consistently reproduce the issue. However if its on Apple's side we can't promise a fix for it.

Thanks,
Anurag

**Comment by fmessina** [comment] 2019-10-28 12:51
We experience the same issue on iOS 11, and adding `libswiftAVFoundation.tdb` as suggested solved the issue. 

Following the issue to uderstand if there is long term solution that can let us remove the added library.

**Comment by jacobmitchinson** [comment] 2019-11-18 12:18
We are also experiencing this issue with the same crash as above. I will add in the AVFoundation lib for now but this is obviously not ideal.

@harryblam Adding you here for visibility.

**Comment by Mayuramipara94** [comment] 2019-12-11 10:22
What was the expected behaviour?

App launches

What happened instead?

App crashes.

Logs:

dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /private/var/containers/Bundle/Application/A5C7DF5B-2B03-40D6-A5F6-769688C27064/WeOne.app/Frameworks/Onfido.framework/Onfido
  Reason: image not found

Onfido SDK (Debug/Release): Both
iOS: 12.0.1
Xcode: 11.1
Device: Iphone 6
Cocoapods: 1.8.4

**Comment by Mayuramipara94** [comment] 2019-12-11 10:26
> I believe this is an Xcode related problem. I am unable to reproduce this issue using our SampleApp located inside this repository using Xcode 11.1.
> 
> The problem might be related to:
> 
> ```
> Command Line Tools
> Known Issues
> When using the Command Line Tools as the active Developer directory, some users may experience random crashes in the Swift compiler. (53582696)
> Workaround: Execute the command sudo rm -f /Library/Developer/CommandLineTools/usr/lib/swift/macosx/libswift*.dylib in Terminal.
> ```
> 
> You can find the known issue in the [Xcode 11 release notes](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_release_notes)
> 
> However given that I haven't experienced the issue myself first hand I am unable to say the above solution will work. Also given the uncertainty of the problem there is no further progress for a solution to this problem yet.
> 
> Anurag

am face same issue with your sample app

**Comment by kinejara** [comment] 2020-01-02 17:52
I am able to reproduce the same issue in my app using iOS 11 and running on an iPhone XR simulator

**Comment by walterholohan** [comment] 2020-02-12 10:17
I am also experiencing the same issue when trying to run an app on iOS 12.1 with Xcode 11.3.1.

The issue was solved by manually adding `libswiftAVFoundation.tbd`, `libswiftUIKit.tbd` and `libswiftCoreAudio.tbd` to `Link Binary Wih Libraries` in xcode. 

If I build to iOS 12.4 the app does not crash.

**Comment by zjohnzheng** [comment] 2020-04-06 03:11
Hello, I had this issue before, and **replacing** 
use_frameworks! _(in your podfile)_
with 
use_modular_headers!
worked for me.
I read somewhere that this problem occured if you are not enrolled in the Apple Developer Program ($99 an year)

**Comment by sdduursma** [comment] 2020-06-17 08:48
We're experiencing the same issue when running on an iOS 12.1 Simulator with Xcode 11.5:
```
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /Users/samuelduursma/Library/Developer/CoreSimulator/Devices/71994566-D40E-4727-824F-DE3CB80813F1/data/Containers/Bundle/Application/597679CC-4322-486F-AB82-0375E146DB8B/felyx.app/Frameworks/Onfido.framework/Onfido
  Reason: no suitable image found.  Did find:
	/usr/lib/swift/libswiftAVFoundation.dylib: mach-o, but not built for iOS simulator
	/usr/lib/swift/libswiftAVFoundation.dylib: mach-o, but not built for iOS simulator
```

I have not been able to test on a real device with iOS 12.1 yet, however we see a significant increase in production crashes on devices running iOS 11.3, 11.4 and 12.1 since we first released a version of the app that included the Onfido SDK. These production crashes produce the following stack trace:
```
Thread 0#0	(null) in __abort_with_payload ()
#1	(null) in abort_with_payload_wrapper_internal ()
#2	(null) in abort_with_payload ()
#3	(null) in dyld::halt(char const*) ()
#4	(null) in dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, un... ()
#5	(null) in _dyld_start ()
```

**Comment by keremgund** [comment] 2020-09-24 11:59
Hello all,
This problem should be fixed with `18.6.0` release. Could you upgrade SDK version and confirm that whether issue resolved ?

Thanks,
Kerem

**Comment by smohamedjavid** [comment] 2020-09-25 09:06
@keremgund Can you update this Wrapper Podspec too?

**Comment by keremgund** [comment] 2020-09-25 09:11
Hi @smohamedjavid,
Are you referring to [React Native](https://github.com/onfido/react-native-sdk) project ?

**Comment by smohamedjavid** [comment] 2020-09-25 09:52
@keremgund Yes

**Comment by keremgund** [comment] 2020-09-28 14:38
@smohamedjavid ok I have seen https://github.com/onfido/react-native-sdk/issues/13 issue which refers to the same problem. We will deliver new release for react-native too but lets continue discussion on https://github.com/onfido/react-native-sdk/issues/13

**Closed by keremgund** 2020-09-28 14:38 UTC
Labels: awaiting response
