### ISSUE TITLE
IOS-sdk sometime returns a success status even though the video has not been captured

### ISSUE THREAD

**Issue by timt** [onfido/onfido-ios-sdk#136] opened 2020-01-30 12:24 UTC
### What was the expected behaviour?

Expected the ios-sdk to only return a success code when the app user has successfully uploaded a video.

### What happened instead?

The sdk returned a success, but when we try to run checks/reports get an error from the onfido api saying there is no video even though we configured the SDK for video. We operate both IOS and android SDK and only seems to be an issue with a limited number of IOS users. When they retry with a new applicant id it typically succeeds.

### Version info:

- Cocoapods 1.8.4
- Onfido SDK (Debug/Release): Release
- iOS: 13.3
- Xcode: 11.3.1
- Device/Simulator: Device - iPhone 8, 8 Plus, 7, 7 Plus, XR and 11 Pro
- Device/Simulator language: Swift

### Integration configuration:

         let config = try OnfidoConfig.builder()
                    .withSDKToken(sdkToken)
                    .withDocumentStep()
                    .withFaceStep(ofVariant: .video(withConfiguration: nil))
                    .build()
            log("Built Onfido config")
            let onfidoFlow = OnfidoFlow(withConfiguration: config)
                    .with(responseHandler: { response in
                        log("Onfido results \(response)")
                        switch response {
                        case let .error(error):
                            rejecter("FAILED", "Onfido failed \(error)", error)
                        case .success(_):
                            resolver("SUCCESS")
                        case .cancel:
                            resolver("CANCELLED")
                        @unknown default:
                          let error = NSError(domain: "com.xxx.error", code: 0, userInfo: [NSLocalizedDescriptionKey: "Onfido gave an unknown responsefailed \(response)"])
                          rejecter("FAILED", "Onfido gave an unknown responsefailed \(response)", error)
                      }
                        presentingViewController.dismiss(animated: true)
                    })

            log("Built Onfido flow, now running....")
            let onfidoRun = try onfidoFlow.run()
            log("Did run Onfido flow will now present")
            onfidoRun.modalPresentationStyle = .formSheet // to present modally
            log("Did set Onfido presentation style")
            DispatchQueue.main.async {
                presentingViewController.present(onfidoRun, animated: true, completion: nil)
            }
            log("Did present Onfido")

### Steps to reproduce:

Use the SDK to do and onfido check, then request report vairant 'Video' from the API, it returns the following message:
    
    {
        "error": {
            "type": "validation_error",
            "message": "There was a validation error on this request",
            "fields": {
                "applicant": [
                    "You must provide a live video to be able to proceed with this check"
                ]
            }
        }
    }

**Comment by anuragajwani** [comment] 2020-01-30 15:24
Hi @timt,

Does success return the FaceResult object?

Could you check if FaceResult object is return in `case .success(let results):` please?

Anurag

**Comment by timt** [comment] 2020-01-30 16:00
Thanks will give that a try

**Comment by timt** [comment] 2020-01-30 18:50
Here's an example of what get returned for us normally, but this is it working correctly on a simulator, the error happens in the wild with a handful of users, so it is not possible to capture what they get on their handsets when it fails!:
```
Onfido success result [Onfido.OnfidoResult.document( Document {
     id=XXX
     href=/v2/applicants/XXX/documents/XXX
     created_at=2020-01-30 16:21:33 +0000
     file_name=onfido-document-XXX.jpg
     file_type=jpg
     file_size=15791
     type=driving_licence
     side=front
 }), Onfido.OnfidoResult.document( Document {
     id=XXX
     href=/v2/applicants/XXX/documents/XXX
     created_at=2020-01-30 16:21:36 +0000
     file_name=onfido-document-XXX.jpg
     file_type=jpg
     file_size=15791
     type=driving_licence
     side=back
 }), Onfido.OnfidoResult.face(FaceResult {
    id=XXX
    href=/v2/live_videos/XXX
    created_at=2020-01-30 16:21:59 +0000
    file_name=Optional("output-30-01-2020_16_<…>

```

**Comment by anuragajwani** [comment] 2020-02-10 16:16
Hi @timt,

We're looking into it. Without ability to reproduce it it will be a little hard to catch the issue at hand. If you find a way to reproduce this problem consistently please let us know.

Thanks,
Anurag

**Comment by anuragajwani** [comment] 2020-02-12 16:29
Hi @timt,

We might have fix for this. We were able to reproduce  a situation where video was not uploaded and success was called. We are issuing this fix in the next version. Hopefully that's the problem you are facing and this will fix it.

I will update this issue once released.

Anurag

**Comment by anuragajwani** [comment] 2020-02-24 16:31
@timt we have released the potential fix. Please test version 16.2.0 of the Onfido SDK. If you continue facing the problem please let us know.

**Comment by keremgund** [comment] 2020-04-01 14:54
Closing the issue due to lack of response. Please create new issue if you think problem persists.

**Closed by keremgund** 2020-04-01 14:54 UTC
Labels: awaiting response, bug
