### ISSUE TITLE
"Please rotate your iPad" screen appears and gets stuck in app only supporting Portrait

### ISSUE THREAD

**Issue by skagedal** [onfido/onfido-ios-sdk#96] opened 2019-05-31 15:25 UTC
### What was the expected behaviour?

Get to the scan-your-passport screen.

### What happened instead?

You get to a screen that says "Please rotate your iPad". See screenshot. But no matter how you tilt your iPad it is not possible to get out of this screen. 

<img width="866" alt="Screenshot 2019-05-31 at 17 21 02" src="https://user-images.githubusercontent.com/1271422/58716068-88015f80-83c8-11e9-984b-37998545a1e6.png">

### Version info:

- Cocoapods (if applicable): 1.6.1
- Onfido SDK (Debug/Release): 11.1.1
- iOS: 12.2
- Xcode: 10.2.1
- Device/Simulator: Now testing on Simulator iPad 12.2, but has also been observed on device
- Device/Simulator language: English

### Integration configuration:

```swift
let config = try OnfidoConfig.builder()
    .withToken(credentials.token)
    .withApplicantId(credentials.applicantId)
    .withDocumentStep()
    .withFaceStep(ofVariant: .photo)
    .build()

let onfidoFlow = OnfidoFlow(withConfiguration: config)
    .with(responseHandler: handleResponse)

let onfidoVC = try onfidoFlow.run()
onfidoVC.view.backgroundColor = .white
present(onfidoVC, animated: true)
```

### Steps to reproduce:

1. Embed Onfido in an app that only supports portrait mode (i.e. by only having Portrait in the "supported orientations" info.plist value)
2. Run app on an iPad.
3. Enter Onfido.
4. On the "Select a Document" screen, turn the iPad so it's in landscape orientation. 
4. Select "Passport"

**Comment by anuragajwani** [comment] 2019-06-03 15:36
Hi @skagedal,

I have tested out our SDK 11.1.1 using our SampleApp (in the repo). I have set to Portrait only and then ran it on the iPad Pro (12.9 inch) simulator using iOS 12.2.

![Screenshot 2019-06-03 at 16 31 49](https://user-images.githubusercontent.com/7071488/58814411-9300fd80-861d-11e9-89fd-840a0560a7e1.png)

The result for capturing passport:
![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2019-06-03 at 16 31 11](https://user-images.githubusercontent.com/7071488/58814438-9d22fc00-861d-11e9-8f66-3551876c946c.png)

Everything looks fine here. If you can please send us a sample project where we can reproduce this problem please.

Thanks,
Anurag

**Comment by skagedal** [comment] 2019-06-03 18:05
Hi! Thanks for the response. I just tried the sample app and could reproduce it there as well. So what you want to do is:

1. Modify the sample app as you described (locked to portrait only) 
2. Launch the app in iPad
2. Rotate the device (simulator) so it's in landscape
3. Press "Verify me"

Bug state now appears.

Here's a diff for how I modified the sample app:
```
diff --git a/SampleApp/SampleApp/Info.plist b/SampleApp/SampleApp/Info.plist
index b2f25b0..4193593 100644
--- a/SampleApp/SampleApp/Info.plist
+++ b/SampleApp/SampleApp/Info.plist
@@ -35,15 +35,10 @@
 	<key>UISupportedInterfaceOrientations</key>
 	<array>
 		<string>UIInterfaceOrientationPortrait</string>
-		<string>UIInterfaceOrientationLandscapeLeft</string>
-		<string>UIInterfaceOrientationLandscapeRight</string>
 	</array>
 	<key>UISupportedInterfaceOrientations~ipad</key>
 	<array>
 		<string>UIInterfaceOrientationPortrait</string>
-		<string>UIInterfaceOrientationPortraitUpsideDown</string>
-		<string>UIInterfaceOrientationLandscapeLeft</string>
-		<string>UIInterfaceOrientationLandscapeRight</string>
 	</array>
 </dict>
 </plist>
diff --git a/SampleApp/SampleApp/ViewController.swift b/SampleApp/SampleApp/ViewController.swift
index 02e50bb..bc0e8d9 100644
--- a/SampleApp/SampleApp/ViewController.swift
+++ b/SampleApp/SampleApp/ViewController.swift
@@ -12,7 +12,7 @@ import Alamofire
 
 final class ViewController: UIViewController {
 
-    private let token = "YOUR_TOKEN_HERE"
+    private let token = "test_MY_TOKEN_REDACTED"
     
     @IBAction func verifyUser(_ sender: Any) {
         
@@ -57,7 +57,7 @@ final class ViewController: UIViewController {
             .withApplicantId(applicantId)
             .withWelcomeStep()
             .withDocumentStep()
-            .withFaceStep(ofVariant: .photo(withConfiguration: nil))
+            .withFaceStep(ofVariant: .photo)
             .build()
         
         let onfidoFlow = OnfidoFlow(withConfiguration: config)

```

Here's a screen recording of the bug:

[onfido-rotate-bug.zip](https://github.com/onfido/onfido-ios-sdk/files/3248861/onfido-rotate-bug.zip)

**Comment by anuragajwani** [comment] 2019-06-05 15:42
@skagedal here is my test result using iPad 12.1.1, SDK 11.1.1, Xcode 10.2:
![Screenshot 2019-06-05 at 16 34 50](https://user-images.githubusercontent.com/7071488/58969646-fc187a80-87af-11e9-93db-45e6bc312ea4.png)

```
diff --git a/SampleApp/SampleApp/Info.plist b/SampleApp/SampleApp/Info.plist
index b2f25b08..d25fa8a9 100644
--- a/SampleApp/SampleApp/Info.plist
+++ b/SampleApp/SampleApp/Info.plist
@@ -35,8 +35,6 @@
        <key>UISupportedInterfaceOrientations</key>
        <array>
                <string>UIInterfaceOrientationPortrait</string>
-               <string>UIInterfaceOrientationLandscapeLeft</string>
-               <string>UIInterfaceOrientationLandscapeRight</string>
        </array>
        <key>UISupportedInterfaceOrientations~ipad</key>
        <array>
~
```

video result:
[ScreenRecording_06-05-2019 16-33-53.MP4.zip](https://github.com/onfido/onfido-ios-sdk/files/3257878/ScreenRecording_06-05-2019.16-33-53.MP4.zip)

One thing I noticed is that even locking the SampleApp to only portrait, the app still rotates. So I tried taking a step further by locking the iPad rotation. I do rotate the iPad even though its not apparent  in the next video. Result:
[ScreenRecording_06-05-2019 16-39-17.MP4.zip](https://github.com/onfido/onfido-ios-sdk/files/3257903/ScreenRecording_06-05-2019.16-39-17.MP4.zip)

I am still unable to reproduce the issue.
Anurag

**Comment by skagedal** [comment] 2019-06-05 17:46
Hi! Yes, you need to disable rotation also for iPads, as in my diff above, so that their is no interface rotation. Then you need to "rotate" the device so that it is physically in landscape mode, even though the interface layout is still portrait. Then you enter Onfido (press "Verify me").

**Comment by anuragajwani** [comment] 2019-06-10 15:24
Hi @skagedal,

I can confirm that I am now able to reproduce the bug. I will be creating a ticket internally. As soon as I have some news I'll update you on the status of this task.

Thanks for reporting the issue,
Anurag

**Comment by keremgund** [comment] 2019-06-24 15:16
Hi @skagedal,

I'm glad to say that we started development to fix this issue and we aim to deliver the fix in our next release. Once we released it, I will give you an update here.

Thanks,
Kerem

**Comment by keremgund** [comment] 2019-07-02 16:45
Hi @skagedal , we just released new version which includes fix for this issue. You can check out 12.2.0 version from https://github.com/onfido/onfido-ios-sdk/releases/tag/12.2.0

Thanks,
Kerem

**Comment by skagedal** [comment] 2019-07-02 19:39
Nice, thanks! We'll give it a spin. 👍

**Comment by keremgund** [comment] 2019-08-05 15:31
Closing the issue. Please open new one if you see the issue still exists.

**Closed by keremgund** 2019-08-05 15:31 UTC
Labels: awaiting response, bug
